version: "2.0"
services:
  web:
    build: docker/php
    container_name: php7_dropstation
    ports:
       - "80:80"
       - "443:443"
    links:
       - db
       - phpmyadmin
    volumes:
      - ./backend:/var/www
  db:
    image: mysql:5.7
    container_name: database_dropstation
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: mysql_server
      MYSQL_USER: magento2
      MYSQL_PASSWORD: gotechnies
      MYSQL_ROOT_PASSWORD: gotechnies
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_dropstation
    environment:
     - PMA_ARBITRARY=1
    links:
     - db
    ports:
     - 8080:80
    volumes:
     - /sessions
